name: Canary Deploy for Lambda
run-name: ${{ github.actor }} start workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package Lambda Code
        working-directory: ./functions
        run: |
          zip -r ../lambda_package.zip .  

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name MyLambdaFunction \
            --zip-file fileb://lambda_package.zip

      - name: Publish New Version
        run: |
          VERSION=$(aws lambda publish-version --function-name MyLambdaFunction --query 'Version' --output text)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure Canary Deployment
        run: |
          aws lambda update-alias \
            --function-name MyLambdaFunction \
            --name live \
            --function-version $VERSION \
            --routing-config '{"AdditionalVersionWeights": {"$LATEST": 0.1}}'

      - name: Finalize Canary Deployment
        run: |
          echo "Waiting for 10 minutes..."
          sleep 300 
          aws lambda update-alias \
            --function-name MyLambdaFunction \
            --name live \
            --function-version $VERSION