name: Canary Deploy for Lambda
run-name: ${{ github.actor }} start workflow
on:
  push:
    branches:
      - main

jobs:
  deploy-canary-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package Lambda Code
        working-directory: ./functions
        run: |
          zip -r ../lambda_package.zip .  

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Update o Create Lambda Function Code
        run: |
          if aws lambda update-function-code --function-name MyLambdaFunctionCanary --zip-file fileb://lambda_package.zip; then
            echo "La función Lambda se actualizó correctamente."
          else
            echo "La función Lambda no existe, creando una nueva..."
            aws lambda create-function \
              --function-name MyLambdaFunctionCanary \
              --runtime python3.12 \
              --handler lambda_function.lambda_handler \
              --zip-file fileb://lambda_package.zip
          fi

      - name: Publish New Version
        run: |
          sleep 10 
          VERSION=$(aws lambda publish-version --function-name MyLambdaFunctionCanary --query 'Version' --output text)
          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Configure Canary Deployment
        run: |
          STABLE_VERSION=$(aws lambda get-alias --function-name MyLambdaFunctionCanary --name prod --query 'FunctionVersion' --output text)
          
          aws lambda update-alias \
            --function-name MyLambdaFunctionCanary \
            --name prod \
            --function-version $STABLE_VERSION \
            --routing-config '{"AdditionalVersionWeights": {"${{ env.VERSION }}": 0.1}}'
        
      - name: Finalize Canary Deployment
        run: |
          echo "Waiting for 2 minutes..."
          sleep 120 
          aws lambda update-alias \
            --function-name MyLambdaFunctionCanary \
            --name prod \
            --function-version ${{ env.VERSION }} \
            --routing-config '{"AdditionalVersionWeights": {}}'